almarklein/timetagger

timetagger/client/demo.md
timetagger/client/front.py

Closes #15 
Two problems:
* The `matchMedia` thing is not fully supported, apparently. IN hindsight I should have put that try-except there from the beginning ...
* There was another issue specific to the demo page, in code that is normally commented out, but I apparently forgot to comment back at some point.

Fix for mobile safari

---

timetagger/client/dialogs.py
timetagger/client/front.py
timetagger/client/style.css
timetagger/client/utils.py

Adds keyboard shortcuts for an easier flow.

Keyboard shortcuts

---

timetagger/client/dialogs.py
timetagger/client/front.py
timetagger/client/style.css

UI/UX tweaks.

---

timetagger/client/dialogs.py
timetagger/client/front.py
timetagger/client/style.css

Also fixes a bug with the "home" keyboard shortcut.

Tweaks to timerange selection

---

Dockerfile
README.md

A bit more docs for developers

---

.github/workflows/ci.yml
README.md
setup.cfg
tasks.py

Also adds an invoke task to bump a release, tag and push it, and release to pypi, which makes my life a bit easier :)

Use invoke for dev tasks

---

timetagger/client/dialogs.py
timetagger/client/front.py
timetagger/client/stores.py
timetagger/client/style.css
timetagger/server/__init__.py
timetagger/server/_assets.py

Various fixes and improvements

---

timetagger/client/dialogs.py
timetagger/client/front.py
timetagger/client/stores.py
timetagger/client/utils.py

Enable coloring tag combinations

---

timetagger/app/front.py

fix that using zoom buttons did not zoom to whole weeks/months

---

Dockerfile
run.py
timetagger/app/dialogs.py
timetagger/app/dt.py
timetagger/app/front.py

Fix DST winter-summer transition on Safari IOS.

---

tests/test_server_apiserver.py
timetagger/server/_apiserver.py

Make running records correctly be queried by GET /records

---

timetagger/app/dialogs.py
timetagger/app/front.py
timetagger/app/utils.py

fix back/forward navigation in months

---

timetagger/app/dialogs.py
timetagger/app/sw.js
timetagger/common/_style_embed.scss

* Closes #81 
* Closes #82
* Fixes accessibility issue (too low contrast for headers)

Fix pomo focus issue

---

timetagger/server/_utils.py

Turn compatible with pyjwt<2.1.0

---

timetagger/app/app.scss
timetagger/app/dialogs.py
timetagger/app/front.py

* Implements tag presets, enabling defining tags before actually using them, and defining tag combis that you use a lot.
* Fix a few bugs and apply some improvements for the tag autocompletion added earlier.

Tag presets

---

docs/docs/webapi.md

Add note about record deletion in web api docs

---

tasks.py
timetagger/app/front.py
timetagger/app/utils.py

Make buttons feel more clickable using a hover effect

---

timetagger/app/dialogs.py

This updates the "Search & manage tags" dialog to include support for plain-text search. The dialog now has a radio button to select between tag-mode and plain-text-mode. The functionality is complete (yes, you can replace text), but it works slighly differently than replacing tags (obviously).

Add plain-text search support

---

timetagger/app/dialogs.py
timetagger/app/front.py

tweaks for small screens

---

tests/test_client_utils.py
timetagger/app/utils.py

Allow typing out-of-range times

---

timetagger/app/dialogs.py

Add more ways to apply grouping in the report dialog

---

timetagger/_config.py
timetagger/app/front.py
timetagger/app/stores.py
timetagger/app/utils.py
timetagger/common/_style_embed.scss
timetagger/server/_apiserver.py
timetagger/server/_assets.py

Also minor tweak to docs about config, and the black formatter has new rules.

Some tweaks to enable code blocks on the website

---

timetagger/app/dialogs.py

Closes #135 
* When you start a new record while one is currently running, stop the current record at the start time of the new record (instead of at now).
* This also applies to resuming a record via Shift+S (#140).
* The initial time when you hit "already running" is just 5 minutes earlier when there is a running record.
* Any records already stopped are not shifted back in time. The argument is that you already (explicitly) stopped them. We cannnot know which is wrong (the old stop time or the new start time). So you'll get overlap which you can easily fix by manipulating records in the timeline..

Stop running records smarter

---

docs/docs/index.md

Refer to new post (yet to be published)

---

timetagger/app/dialogs.py

Closes #150.
This bug was really an oversight on my part.

Fix tag-filtering for no-grouping in report dialog

---

timetagger/app/dialogs.py
timetagger/app/front.py

Closes #149. Also added N for the snap-to-now shortcut, since Macs don't have home/end :)

Snap to now no longer snaps to a day when zoomed in

---

timetagger/app/front.py

Closes #104
When you click on the timeline:

Create a new record by dragging in timeline WIP

---

timetagger/app/front.py

Nothing serious, but it bothered me a bit.
Keep up the great work, love it!

fix typo in frontend

---

timetagger/app/dialogs.py

I found it annoying that presets are on the top of the autocompletion list, when you're not interested in a preset at that moment. I came to the conclusion that they don't mix well in a single autocompletion list because its hard to tell what the user wants.
So let's make it explicit: type "#" for recent tags, and "##" for presets. The extra "#" is stripped when you accept the completion.

Preset autocompletion kicks in when using ##

---

timetagger/app/dialogs.py

Make date input fit on Brave browser

---

timetagger/app/front.py

More tweaking after #177 and #178.

Design tweaks

---

timetagger/app/dialogs.py

enable edit button after selecting preset or recent tag

---

timetagger/app/dialogs.py

Closes #174
When the autocompletion is active, you can now toggle between recent tags and presets, by pressing '#', also if you've already typed something behind the hash symbol.

Toggle between presets and recent tags by typing #

---

README.md
timetagger/app/front.py

* Some more details in the readme.
* Fix that demo/sandbox did not have that description below the menu button.

Tweak readme and fix minor issue

---

timetagger/app/front.py

The code for the overview panel was quite complex, because the visualization had different needs when this was still called TimeTurtle. This PR is a big cleanup that greatly simplifies that code.

Refactor overview panel

---

timetagger/app/utils.py

Fixes #192 
We were using the window size, but its much more reliable to check the screen size. I also looked at user agent parsing (see e.g. [here](https://stackoverflow.com/questions/3514784/), but I think checking screen size makes more sense for what we want to achieve.

Better desktop detection

---

timetagger/app/app.scss

Fixes #194. Weird, but it works.

Webapp full screen

---

timetagger/common/_style_embed.scss

Hide overflow to prevent flicker due to tooltip

---

timetagger/app/dialogs.py
timetagger/app/front.py
timetagger/common/_style_embed.scss

Closes  #162
This adds CSS for multiple "width modes". In the settings the width mode can be select.
The 100px and 1500px are rather arbitrary. Could add more modes later. Let me know if you have an idea / use-case for another width-scaling-mode!

Option in settings to configure app width

---

timetagger/app/_template.html
timetagger/common/_style_embed.scss

A better way to do #208, that fixes #213.

Implement overflow-hiding differently

---

timetagger/app/front.py

Closes #242. This does make the buttons appear a wee bit narrower, and changes the appearance of the shadows slightly too.

Fix that buttons appeared larger than they are

---

tests/test_client_dt.py
timetagger/app/dt.py

Dont assume integer timezone offset

---

deploy/docker-compose.yml

Mention .env file quotes

---

timetagger/__main__.py

Add health endpoint

---

timetagger/app/dialogs.py

Dont reset start time in record dialog on each mode change

---

timetagger/app/dialogs.py
timetagger/app/dt.py

Fix timezone indicator in settings

---

timetagger/app/dialogs.py

Clarify autocomp toggle

---

timetagger/app/front.py

* Clicking on colorbands with one tag just goes to the tag dialog. Closes #258.
* Clicking on the bar itself selects all tags of that bar. Closes #259.

Click ux in overview

---

timetagger/app/front.py

Improve sync indicator icons a bit

---

timetagger/app/dialogs.py

Closes #266  (low hanging fruit :))

More descriptive button text

---

timetagger/app/dialogs.py

Improvements to import logic

---

timetagger/app/dialogs.py

Show recent descriptions

---

docs/docs/index.md
timetagger/app/front.py

So when there is no connection, this is made more clear. Also mention the indicator icon in the dev docs.
Closes #273. See also #252.

Use red color when sync is in error

---

timetagger/app/dialogs.py

Search should not show hidden records

---

timetagger/app/dialogs.py

Dont show recent descriptions in search

---

timetagger/app/dialogs.py

Show clickable links in description

---

timetagger/app/front.py

Fix that bottom of buttons were not clickable

---

tests/test_client_dt.py
timetagger/app/dialogs.py
timetagger/app/dt.py
timetagger/app/front.py
timetagger/app/utils.py

Mode can be configured in the setting dialog.

Can show duration as 2h30m

---

timetagger/app/dialogs.py
timetagger/app/front.py
timetagger/app/utils.py

Closes #148.
Offset can be specifief in the settings dialog. When the offset is zero, the behavior is as it was. Otherwise, the "today" button will not get grayed out. You can click the button to toggle between the real today and the offset.

Implement today snap offset

---

timetagger/app/dialogs.py

Refactored the search dialog a bit.
* Plain text is now split in words.
* Words and tags can be excluded by prepending a "!". Closes #235.
* A text below the input field shows the search rules for clarity. The button text is unchanged. This closes #289.

More powerful search

---

.github/workflows/ci.yml
timetagger/app/dialogs.py

Closes #295
Also had to update CI, because Python 3.6 was dropped.

Fix that clicking on autocomp did not work if dquotes are in the description

---

timetagger/app/front.py

Snap to dayoffset by default

---

timetagger/app/dialogs.py

CSV report adheres better to SCV spec

---

timetagger/app/dialogs.py

Wrap long descriptions in PDF report

---

timetagger/app/dialogs.py

Closes #321. Also changed the "To"  field in the PDF to show the last date included in the document, instead of the first date beyond the range.

The pdf and csv exports now include the date range

---

timetagger/app/dialogs.py

Fix that linebreaks in pdf report swallowed a word

---

README.md

Put quotes around env var in readme

---

timetagger/app/dialogs.py

Fix that using uppercase chars in the search field breaks the search

---

timetagger/app/dialogs.py
timetagger/app/front.py

Snap to today when resuming from a record earlier than today.

---

timetagger/app/dialogs.py
timetagger/app/dt.py
timetagger/app/front.py

Enable representing long durations as e.g. 1d3h20m

---

timetagger/app/dialogs.py
timetagger/app/front.py
timetagger/app/utils.py

Closes #343.
Also add more options for today's start, up until 9:00.
This is implemented as an offset from the end of the day. This behaves better in summertime/wintertime transitions.

Enable showing today as 12h range

---

timetagger/app/dialogs.py

Search dialog links to goto date are proper hrefs now

---

timetagger/app/dialogs.py
timetagger/app/front.py
timetagger/app/stores.py

I did some research that revealed that a large portion of new users create very little records (zero or one, mostly) and then quit. I suspect that this is because they don't know where to start and how things work. I'm working on a series of improvements to help new users in the very early stages.

Better in-app tips for fresh users

---

timetagger/app/utils.py

I though that I fixed this, but apparently we need some heavier machinery.

No tooltips on mobile devices

---

.github/workflows/ci.yml
.github/workflows/dockerimage.yml

Fix nonroot image being 'latest'

---

timetagger/app/dialogs.py

Fix show-hours in decimals

---

timetagger/app/dialogs.py

Fix report: grouping by time

---

timetagger/app/front.py
timetagger/app/utils.py

Make ResizeObserver logic compatible with all browsers

---

timetagger/app/dialogs.py

Fix that the total was the taking tag filters into account

---

timetagger/app/front.py

Can unselect tags by clicking on them

---

tests/test_server_assetserver.py

The 404 message for the in-memory asset util changed slightly.

Update test for new asgineer

---

timetagger/app/stores.py

Fix recursion error due to early dates

---

timetagger/app/front.py

Tweak unselecting with backspace

---

timetagger/pages/login.md

The autocompelte for username + password works now in the browser (also on mobile browsers)

Add a form html tag to the login form enabling autocomplete for password managers
