timetagger/__init__.py
timetagger/client/front.py

Improvements to overview panel

---

timetagger/client/dialogs.py
timetagger/client/front.py
timetagger/client/style.css

Closes #30, closes #27, closes #40, closes #39

Refactor the record dialog and workflows to start/stop/create a record

---

timetagger/client/dialogs.py
timetagger/client/front.py
timetagger/client/utils.py

Several UX improvements

---

tests/test_client_recordstore.py
timetagger/client/stores.py

Closes #48
The issue was that when a record is `put` in the store, its previous version is first removed. However, a deleted record (which is not actually deleted, but hidden) is not present in the heap, so removing it fails. I added tests that failed because of this, and then fixed it by guarding against this case.
In case you've experienced this error, there should not be any implications. The error occurs when the server "confirms" the update of the record.

Prevent error popup after deleteting a record

---

timetagger/client/front.py

This is a bit of an addendum to #58
With the last changes, the duration-text for a running record would be prone to sticking out. This fixes that, using the same alignment as we already did in the overview panel. It also shows the second in a lighter color.

Tweak duration text

---

timetagger/app/app.scss
timetagger/app/dialogs.py

Closes #53
Instead of providing a series of recently used tags, an autocomplete popup is used that:
* when only `#` is typed, shows recently used tags, ordered by relevance.
* when more chars are typed, shows matches based on all known tags.
The advantage is that the suggested tags is not cut-off arbitrarily. Well, it still only shows tags from the past 12 weeks. But the autocompletion will suggest based on all tags ever used. One downside is that you have to type `#` to invoke the suggestion. This may be resolved later.

Refactor how tags are suggested

---

timetagger/app/dialogs.py

* When typing out a tag and then pressing a space, the autocompletion popup was not hidden. This fixes that.

Fix that autocomp was not hidden

---

timetagger/app/app.scss
timetagger/app/dialogs.py
timetagger/app/front.py

Navigation tweeks

---

tests/test_client_utils.py
timetagger/app/dialogs.py
timetagger/app/utils.py

Closes #116 
* Prevents times from overflowing into the next day.
* Prevent snapping the *other* time during editing a time.
* Fixes to when the duration is periodically updated.

Fixes to startstop time editing

---

tests/test_server_apiserver.py
timetagger/app/dialogs.py
timetagger/app/stores.py
timetagger/server/_apiserver.py

* The record dialog does not allow more than 255 chars, and when it happens a warning occurs. Closes #127.
* The preset dialog does not allow more than 8192 chars`*` (32x as much as before) and warns when its over. Closes #126.
`*` technically the limit applies to the json-serialized version of the preset field.

Fixes to handling maximum input

---

timetagger/app/dialogs.py

Closes #137
This is an attempt to fix #137. It seems to work fine, except I don't know how this will work out when you have *a lot* of presets. The way that the autocompletion works is that it only considers one word/tag, so if you type e.g. "#foo #ba", and you have a preset "#foo #bar" and accept it, your text will be "#foo #foo #bar". This will need some thought.

Show presets in autocomp list

---

timetagger/app/dialogs.py
timetagger/app/utils.py

Closes #153.
Each line is still parsed, and only the tags remain, but the tag order is not changed. Empty lines are now also allowed (and are not removed).

Make preset dialog less anoying

---

timetagger/app/front.py

In an earlier incarnation, the overview had a 3D look with bars being "higher" (and taking more space) when they'd represent more time. The required space to accommodate for that was still reserved.
This PR disables some of the inset-related logic, but not all - if we ever want *some* form of inset again, then it would be really hard to fiddle it back in. Maybe at a later stage I have the guts to clean this up more thoroughly.

Remove name-logo on small screens, and make more use of available space

---

timetagger/app/dialogs.py

Closes #161.
I went with separate buttons for recents and presets. That way, the lists are somewhat shorter, which is nice if you really only use the mouse. For ppl using the keyboard its no problem is the list is long because it's combined, because they'll type one or 2 chars and reduce the list to just a few items.

Bring back buttons to show recents and presents

---

timetagger/app/front.py

And also indicating which record is running in the timeline and overview.
Closes #159
The thicker borders are quite subtle, but together with the secs being shown I think it does the trick. Let me know if you think it needs a bit more weight.

More subtle hint about when a record is running

---

timetagger/app/dialogs.py

Closes #175
Spelling was turned off, because tags are usually not valid spelling. But if you add more text, you'd want that text to be spell-checked. Let's try turning it on.

Lets try turning spellcheck on

---

timetagger/app/utils.py

They get in the way, and stick around without disappearing.

Disable tooltips on touch events

---

timetagger/app/dialogs.py
timetagger/app/front.py

Replaces the separate tag-color dialog and target-dialog with two new dialogs: one for tag combis and one for individual tags.
This closes #139. It forms the basis for more improvements, e.g.:
* A rename button.
* A button to see all records for that tag/tag combi, as discussed in #139.
* Setting tag priority #128 
* Improved targets / multiple targets #121

Refactor tag config dialogs

---

tests/test_client_utils.py
timetagger/app/dialogs.py
timetagger/app/front.py
timetagger/app/stores.py
timetagger/app/utils.py

Closes #128, by introducing tag-priority, and enabling hiding secondary tags in the report. This PR also lays the basis for #121, by making it possible to store multiple targets per tag.

Add tag priority feature

---

timetagger/app/app.scss

Due to the fix in #198, on wider screens, the layout was incorrect. This fixes it by only using the viewport measure only for the height.

Fix layout regression

---

deploy/docker-compose.yml

Closes #224
This is especially problematic for the BCrypt hashes, since these always have 3 dollar signs. I briefly considered replacing them in the cred.html, but then they're not real BCrypt hashes anymore, and it would be confusing. This is a limitation of docker-compose, so let's just document it.
Will also adjust the blog post.

Dollar signs must be escaped in docker compose files

---

timetagger/app/dialogs.py

Closes #226
Also fixes another regression that I had not seen yet: when you select a tag using the recents-button, and then another, the second would overwrite the first.

Fix that autocomp could not be closed when invoked using the button

---

timetagger/app/dialogs.py

Closes #243. This will probably do the trick. I confirmed that previously the input element has focus, even though the dialog is gone. With this change the canvas gets focus once the (last) dialog is closed.

Return focus to canvas when a dialog is closed

---

timetagger/app/stores.py

Prevent closing the tab when there are unsaved changes

---

docs/docs/index.md

Hi Almar,
as per your suggestion, I added a link to my blog article for autostarting TimeTagger on Linux using systemd. 
Greetings,
-Thomas

Added link to blog article on autostarting TimeTagger.

---

requirements.txt
timetagger/__main__.py
timetagger/_config.py

Allowing CIDR-ranges in the TRUSTED_PROXIES specification makes it easy to specify a range of trusted IP addresses.
My use case being the proxy auth frontend and timetagger both running in kubernetes where the pods/containers get a random IP address within a specified subnet which would make it tedious to specify them one-by-one.
Specifying `proxy_auth_trusted` works exactly like before, with the exception that iptools handles parsing to allow CIDR addresses.
A ready-made container which I used to test the changes in my kubernetes cluster is available at https://hub.docker.com/r/rynoxx/timetagger
[iptools source](https://github.com/bd808/python-iptools)
[iptools documentation](https://python-iptools.readthedocs.io/en/latest/)

Use iptools to allow specification of CIDR IP ranges

---

timetagger/app/dt.py
timetagger/app/front.py

Closes  #315
* Time is displayed as `-20m10s` instead of something like `-20m-10s` with numbers that are not correct.
* You can drag the flap op the record in the timeline. When you do this, the time snaps to now.

Better support for running records with a negative duration

---

timetagger/app/dialogs.py

Closes #301 
This simplifies the autocompletion code and behavior:
* For a recent description, the text is simply replaced.
* For both tags and presets, the new text is appended/inserted.
* Spaces are added before and after to separate the inserted text with the existing text.
* New cursor position is one space beyond the newly introduced text, ready to receive more input.

Refactor autocompletion behavior

---

timetagger/app/dialogs.py

* Fixes that the duration was not displayed correctly with the "hms" notation.
* Prevent "Unhandled Promise Rejection", closes  #323

Small fixes to Pomodoro

---

timetagger/app/dialogs.py

Closes #335.
Also closes an issue where selecting an item from the recent descriptions, the text is not replaced but appended. The problem was the test `if not text.startswith("#")` which intended to check whether the new text was an earlier description, but this of course fails for descriptions that simply start with a tag 🤷 . Now we track whether the autocomp list comtains descriptions and use that flag.

Fixes to autocomp

---

timetagger/app/dialogs.py

* Don't update stuff until user is done setting the date. Closes #346.
* Don't show seconds in timer edit dialog (except in the duration field when the timer is running).

Improvements to datetime input dialog

---

timetagger/app/front.py

Closes #345. Took the easy route and just added a space.

Add a space before 0h to avoid mental concat with the date that preceeds it

---

timetagger/app/dialogs.py
timetagger/app/front.py
timetagger/app/stores.py

This makes it much easier to detect errors, and also helps clear up some of the confusion when a trial has expired.

Clicking the sync button now shows the error (if there is one)

---

timetagger/app/app.scss
timetagger/app/dialogs.py
timetagger/app/front.py
timetagger/app/stores.py

Previously, when the trial was expired, the app still worked, but changes were simply not pushed to the server. This was confusing, because users may not take notice of the sync icon showing an exclamation mark and just carry on. This PR allows the server the put the app in readonly mode so the dialogs prevent making changes, resolving the confusion.

Implement a read-only mode (for when the trial has expired)

---

.github/workflows/dockerimage.yml

This PR improves CD action to build an arm64 Docker image that could be used on Raspberry PI (#257). I based it on the [offical Docker documentation](https://docs.docker.com/build/ci/github-actions/multi-platform/). The change was tested on my fork, where I was able to build an arm64 image (see https://github.com/maresmar/timetagger/pkgs/container/timetagger/97423218?tag=v0.0.2 and the [workflow log](https://github.com/maresmar/timetagger/actions/runs/5126767620/jobs/9221673889).
The arm64 image is running fine on my Raspberry Pi 3+ (with Raspbery OS 64bit, 2023-02-21).

Add docker image for arm64

---

tests/test_client_dt.py
timetagger/app/dialogs.py
timetagger/app/dt.py
timetagger/app/front.py

Two glitches and one improvement actually:
* In the display of the time left on the current pomodoro work/break, the code assumed the "hh:mm:ss"  notation and simply stripped off the first two characters. But that fails for e.g. "4h12m01s".
* When not showing seconds, the minutes are rounded (1m28s becomes 1m, 1m32s becomes 2m). But there was some code in two places that took the duration string both with and without seconds and used the two to draw the seconds in a different color. But the effect was that 1m32s was then displayed as 2m32s. Oops.
* When the duration is less than a minute, the duration is expressed in seconds. So 42 seconds would be "42s" instead of "1m", and 12 seconds would be "12s" instead of "0m". Note that when using "hh:mm" notation (via the settings), it will still …

Fix glitch in display of duration

---

timetagger/app/dialogs.py

Closes #361
You can now also use https://timetagger-url/app/#date=2023-01-01  to make the timelinenavigate to a predefined date. This makes it easier for other tools to interact with TimeTagger, e.g. by providing links to specific days.

In the search dialog you can now go to the date of each search result.

---

timetagger/app/dialogs.py
timetagger/app/utils.py

Closes #304, closes #348.
This refactors the grouping mechanics in the report dialog. There are now two dropdown buttons. One to select the primary grouping, and one for the time period. You can now also group by description, and by different periods.

Improvements to report grouping

---

.github/workflows/dockerimage.yml
deploy/repo.Dockerfile
deploy/repo.nonroot.Dockerfile

Dear @almarklein, I just started to use your awesome `timetagger` app for my personal time tracking needs. Great project I really like it!
I noticed that the ghcr published images and also the other container variants make use of the `root` user with `uid` and `gid` of `0`.
In order to make container escapes harder and follow security best-practices I introduced an unprivileged service user named `timetagger` with `uid` and `gid` of `1000` to the `repo.Dockerfile`.
This might be considered as a breaking change as existing self hosted installations probably need to alter their persistent data in order to be able to use the unprivileged variant.
Before going forward with this change, maybe also on the other container variants, I wanted to get your feedback first if this contribution is …

Switch containers to unpriviliged service user

---

timetagger/app/dt.py
timetagger/app/front.py

When the app loads, it queries the records from memory and the server. It therefore has zero records for a brief period, which caused the newby-tips to be shown for a moment, which feels a bit glitchy. This fixes that. The tips appear somewhat later, which makes them stand out even better, I suppose!

Tweak when startup tips are shown

---

timetagger/app/dialogs.py
timetagger/app/front.py

Hey @almarklein,
searching through the issues of timetagger I found #406.
As I wanted to familiarize myself with the codebase this looked like a quick win.
This PR adds Y/y as a shortcut to zoom the current view to the whole year.

Added 'Y' to select year view as shortcut

---

README.md
deploy/docker-compose.nonroot.yml

Add documentation for nonroot Docker variant

---

timetagger/app/app.scss
timetagger/app/front.py
timetagger/app/utils.py

The app would sometimes hang, and it looks like it is possible to reproduce the hanging by resizing the window. This takes a couple of measures to prevent the hanging due to negative sizes, and also adds some guards to while loops so they always exit.
Also looked into a better way to determine the physical canvas size, so it's laid exactly ontop of the physical pixels (when possible).

Fix hang and crispier look

---

timetagger/app/front.py
timetagger/app/utils.py

Closes #407. Implementing a scrolling mechanism when the number of items in the overview don't fit.
Working, but not quite happy yet 🤔

Scrolling the overview

---

timetagger/app/utils.py

Since I still saw occasional hangs (when resizing, on Firefox/MacOS) after #418, maybe this'll help.

On resize use update instead of draw

---

timetagger/app/dialogs.py

Closes #403
The idea is to show presets that match the word typed in the description input. This then allows typing/selecting a tag, then pressing the preset button, and quickly get the preset you need, even if you have a lot. This can be especially helpful on mobile (see #403).
To prevent unwanted "matches", this search feature only works when the ds input only contains a single word/tag.

Preset drowndown filters based on tags in ds

---

timetagger/app/app.scss
timetagger/app/front.py

Closes #425 
The buttons now respond to a click instead of down, and the overview can be scrolled by dragging. ~Also allows to scroll the overview up a bit more, in case the bottom of the app is obscured by a home bar.~ Fixed that the app takes up the full space, without having a bottom margin on iPhone or the bottom part of the app hidden by the Android navigation bar.
This also fixes #194 again, undoing the change in #198 where `100vh` was used instead of `100%`. The trick was to removing the padding of the parent element. [This post](https://stackoverflow.com/a/76979555/2271927) helped me find the solution.

Fix overview scrolling on mobile

---

timetagger/app/app.scss
timetagger/app/dialogs.py
timetagger/app/front.py

Tweaks for better experience on mobile

---

timetagger/app/dialogs.py
timetagger/app/utils.py

Closes #408.
This way, the shown (rounded) numbers do actually add up to the totals (previously the summing was done on second-precision durations, leading to round-off errors, see #408).
----

Report sums rounded durations

---

timetagger/common/cred.html

Not a big deal, but Google Search Console was complaining about this info missing.

Add viewport metadata to /cred

---

timetagger/app/dialogs.py

On iOS there is a common feature on all browsers where inputs with text under a certain size cause the view to zoom in to compensate. On a Progressive Web App this zoom cannot be reverted, requiring the app to be re-opened.
This pull request simply sets the inputs I found to have relative sizes to fixed 16px size to prevent the issue from happening.
Demonstration of the issue:
https://github.com/almarklein/timetagger/assets/72520178/48c91ccb-d626-4b03-9f1a-8494e470de5c

Fixes iOS zoom issue

---

timetagger/app/dialogs.py
timetagger/app/dt.py
timetagger/app/front.py
timetagger/app/utils.py

Closes #417 
Related issue #121 
Added option to set work week to:
- Monday - Friday
- Monday - Saturday
- Monday - Sunday

Add option for Monday-Friday week

---

timetagger/app/dialogs.py
timetagger/app/utils.py

Enable notifications

---

timetagger/app/front.py

To me the "now line" was to dark in the darkmode, yet in the lightmode it is quite visible. So I changed the color a tiny bit to the text color. Maybe you find this tweak useful. (=

Changed that the "now"-line was barely visible in darkmode

---

timetagger/app/timetagger_manifest.json

Without this on my Android phone separate webapp had lack of controls in the bottom of screen, so it wes difficult to close it or switch to another application.
With standalone setting it works just as ordinal Android application.

Use standalone display for better user experience on Android.

---

timetagger/app/front.py

For me it appeared useful to make "stop" button take color of current activity tag, so I can quickly check whether I made 
record after switching activity. May be it can be merged "as is", may be some settings should be added - I open for discussion on this topic.
Here is how it looks after these changes:

Propoal: Set stop button color based on running tag.

---

timetagger/app/dialogs.py
timetagger/app/front.py

I reset my branch, since with my recent PR #480 I accidentally had all my recent changes combined in one PR, which was not my intention. Also I now added things to the GUI to properly reflect the new feature.

Backspace can unselect all tags now

---

timetagger/app/front.py

If it's after midnight but before the day start offset time, then snapping to "today" should snap to the previous offset day, rather than the new offset day that hasn't started yet.

Snap to previous day if we haven't passed the dayoffset yet

---

timetagger/app/front.py
timetagger/app/stores.py

Just a few records that stick together in a cluster.
The margin between the records decreases as more records are in the cluster:

Compact clusters with many records in timeline

---

tests/test_config.py
timetagger/__main__.py
timetagger/_config.py

This adds a check in `get_webtoken_localhost()` whether the server is actually hosting on localhost.

Add check for localhost auth

---

.github/workflows/ci.yml
deploy/pip.Dockerfile
deploy/repo.Dockerfile
deploy/repo.nonroot.Dockerfile
timetagger/__main__.py
timetagger/server/_assets.py

Hi @almarklein,
I took the time and tried to upgrade TimeTagger and its container images to Python 3.13.
Additionally the CI has been upgraded to also test all currently supported Python versions up to Python 3.13. Old and unmainted versions have been removed.
Minor code changes were nessecary in order to make the codebase Python 3.13 ready and get rid of deprecated function calls.
The work and testing is not fully done yet I think but before putting more work into this I wanted to get some feedback from your side if it is worth the effort.
Cheers and merry christmas 🎄,
Daniel

Bump to Python 3.13

---

setup.py

A little post-work for #521.
I removed the Pyhton version classifiers from `setup.py` for unmaintained Python versions and added recent ones until `3.13`.

Updated Python version classifiers in setup.py

---

.github/workflows/dockerimage.yml
deploy/docker-compose.nonroot.yml

As requested in #411 I added a `latest-nonroot` tag to the nonroot image variant.
I also fixed the latest tag nonroot overwrite issue differently (disabling the push of the latest tag for the non-root variant) in order to allow the jobs to run in parallel again and to not rely on the tag overwrite to fix this.

#411 - Added latest-nonroot image tag

---

tasks.py
timetagger/app/stores.py

Helps prevent the case where a user switches tabs after making a change, causing the data not to be synced when that tab is killed. See #439

Shorter timeout after editing record

---

timetagger/app/front.py

The logic in `_get_snap_range` breaks when the range is set to a 24-hour period that starts less than 12 hours after the the EST/EDT transition. For example, if `t1` is `2025-03-09 06:00 EDT` and `t2` is `2025-03-10 06:00 EDT`, then the unrounded `t3` is `0.5 * (2025-03-08 18:00 EST + 2025-03-09 18:00 EDT) = 2025-03-09 06:30 EDT`, which gets rounded up to 07:00. Then once the target range changes to 07:00, the snap range gets rounded up to 08:00, and so on until it hits 15:00 and the snap range logic works again.
I'm breaking the loop by adding a simple "if it ain't broke, don't fix it" check to `_get_snap_range`: If the current target range already has the correct length and alignment, then we don't attempt to do the possibly-broken math to recalculate it. Maybe there's a fancier way to …

Prevent summer/wintertime changeover from sending the snap range logic into a loop

---

timetagger/app/dt.py

During the week following the EST/EDT changeover, `dt.floor()` at the week level produces results one day earlier than it should due to the missing hour messing up the calculations. Rather than subtracting a number of seconds, we should directly decrement the day of the month instead.

Prevent summer/wintertime changeover from breaking week floor calculation
